name: Deploy to repository.silvo

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'MikeSiLVO/skin.aeon.nox.silvo'
    uses: MikeSiLVO/workflows/.github/workflows/deploy-to-repo.yml@v1
    with:
      channel: piers
    secrets: inherit
