name: Make Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.repository == 'MikeSiLVO/skin.aeon.nox.silvo'
    permissions:
      contents: write
    uses: MikeSiLVO/workflows/.github/workflows/make-release.yml@v1
    secrets: inherit
